PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
    schema:Person ?p ?o .
    ?prop ?p2 ?o2 .
} WHERE {
    schema:Person rdf:type rdfs:Class ;
        ?p ?o .
    ?prop schema:domainIncludes schema:Person ;
        ?p2 ?o2 .
}